### ISSUE TITLE
Animation - API or plugin?

### ISSUE THREAD

**Issue by sekodev** [coronalabs/corona-docs-plugins#6]
I just found out about the `animation.*` library. I didn't know there was a library with that named since the starter guides were not there when I started out years ago :)

Anyway, it's listed as a plugin but looking at the docs it seems more like a library. Is there a reason that it's not listed with other libraries in API reference? Shouldn't it be removed from plugins and moved to API reference?

https://docs.coronalabs.com/plugin/animation/

**Comment by coronarob** [comment]
There was a lot of discussion about if it should be a core library or be a plugin. Being a plugin won. The team at the time didn't want to bloat the core library and felt that this would be better as an add-on or plugin.

Should it be moved? Not my call, but if it's something you have to add as a plugin (i.e. build.settings code) and isn't available in the core, then no, it should stay a plugin and be documented as a plugin. Should @Shchvova want to add it to the core, then it makes sense to move it into the core API docs.

Just a little history...

**Comment by sekodev** [comment]
Hi Rob! Glad to see that you are still around. Hope everything's good and well.

It's been more than 7 years since I started with Corona SDK and to be honest, I didn't even know such thing existed in the first place but while looking at the docs, I've seen a reference to it. After checking the corresponding documentation it seemed to me like it's in the core library because I couldn't see a reference to `build.settings`. 

Also, I should note that there is not a reference to it from neither the API Reference nor the Plugins page. It only seems to be referenced from [here](https://docs.coronalabs.com/guide/media/animationLibrary/index.html).

**Comment by coronarob** [comment]
I'm not really still around, but I do still get emails from GitHub about what's going on. I love Corona too much to completely ignore it. We announced it back in 2018: https://coronalabs.com/blog/2018/11/02/introducing-the-new-animation-plugin/
but really didn't say much about it afterwards. It's in the plugin index under the "Utilities" section. Probably pretty poorly placed there. http://docs.coronalabs.com/plugin/index.html

It might be worth creating another category instead of dumping things like that into "Utilities".

**Comment by sekodev** [comment]
I just saw the listing where you mentioned. Also, just thought about looking at the free plugins directory and found out it was there. It may be a better idea to add information about `build.settings` instead of some big changes. Thanks for the information Rob. That cleared things up for me.

(I couldn't get it to work on require phase but I'll try again later.)
